pull_request_rules:
  - name: Backport to humble branch
    conditions:
      - base=main
      - label=backport-humble
    actions:
      backport:
        branches:
          - humble
      label:
        add:
          - humble

  - name: Backport to iron branch
    conditions:
      - base=main
      - label=backport-iron
    actions:
      backport:
        branches:
          - iron
      label:
        add:
          - iron
