pull_request_rules:
  - name: Backport to humble branch
    conditions:
      - base=main
      - label=backport-humble
    actions:
      backport:
        branches:
          - humble
        labels:
          - humble

  - name: Backport to jazzy branch
    conditions:
      - base=main
      - label=backport-jazzy
    actions:
      backport:
        branches:
          - jazzy
        labels:
          - jazzy
