publisher_forward_velocity_controller:
  ros__parameters:

    publish_topic: "forward_velocity_controller/commands"
    wait_sec_between_publish: 5

    goal_names: ["vel1", "vel2", "vel3"]
    vel1: [0.0, 0.0, 0.0, 0.0, 0.0, 0.5]
    vel2: [0.0, 0.0, 0.0, 0.0, 0.0, -0.5]
    vel3: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
