name: Binary Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 4 * * *'

jobs:
  binary:
    name: binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: rolling, ROS_REPO: main}
          - { ROS_DISTRO: rolling, ROS_REPO: testing}
          - {ROS_DISTRO: galactic, ROS_REPO: main}
          - {ROS_DISTRO: galactic, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver-not-released.${{ matrix.env.ROS_DISTRO }}.repos
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr'
      NOT_TEST_BUILD: true
      NOT_TEST_DOWNSTREAM: true
      IMMEDIATE_TEST_OUTPUT: true
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      BASEDIR: ${{ github.workspace }}/.work
    steps:
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - name: prepare target_ws for cache
        if: ${{ always() && ! matrix.env.CCOV }}
        run: |
          du -sh ${{ env.BASEDIR }}/target_ws
          sudo find ${{ env.BASEDIR }}/target_ws -wholename '*/test_results/*' -delete
          sudo rm -rf ${{ env.BASEDIR }}/target_ws/src
          du -sh ${{ env.BASEDIR }}/target_ws
