name: Binary Build
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '43 8 * * *'

jobs:
  foxy_binary:
    name: foxy binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: main}
          - {ROS_DISTRO: foxy, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver-not-released.foxy.repos
      DOCKER_RUN_OPTS: --network static_test_net
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
      IMMEDIATE_TEST_OUTPUT: true
    steps:
      - uses: actions/checkout@v1
      - name: start ursim
        run: |
          .github/dockerursim/build_and_run_docker_ursim.sh
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  galactic_binary:
    name: galactic binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: galactic, ROS_REPO: main}
          - {ROS_DISTRO: galactic, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver-not-released.galactic.repos
      DOCKER_RUN_OPTS: --network static_test_net
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
      IMMEDIATE_TEST_OUTPUT: true
    steps:
      - uses: actions/checkout@v1
      - name: start ursim
        run: |
          .github/dockerursim/build_and_run_docker_ursim.sh
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  rolling_binary:
    name: rolling binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver-not-released.rolling.repos
      DOCKER_RUN_OPTS: --network static_test_net
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
      IMMEDIATE_TEST_OUTPUT: true
    steps:
      - uses: actions/checkout@v1
      - name: start ursim
        run: |
          .github/dockerursim/build_and_run_docker_ursim.sh
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
