name: Coverage Build
on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: coverage build
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:jammy
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: rolling
      ros_version: 2
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          # build all packages listed in the meta package
          package-name:
            ur
            ur_bringup
            ur_controllers
            ur_dashboard_msgs
            ur_moveit_config
            ur_robot_driver
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/Universal_Robots_ROS2_Driver-not-released.${{ env.ROS_DISTRO }}.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          skip-tests: true
      - uses: codecov/codecov-action@v3
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
