name: Humble Semi Binary Build Main
on:
  workflow_dispatch:
    branches:
      - humble
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 5 * * *'


jobs:
  binary:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: humble
      ros_repo: main
      upstream_workspace: Universal_Robots_ROS2_Driver.humble.repos
      ref_for_scheduled_build: humble
