name: Iron Semi Binary Build Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - iron
  push:
    branches:
      - iron
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 5 * * *'

jobs:
  iron_semi_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: iron
      ros_repo: testing
      upstream_workspace: Universal_Robots_ROS2_Driver.iron.repos
      ref_for_scheduled_build: iron
