name: Reusable industrial_ci workflow
# original author: Denis Štogl <denis@stoglrobotics.de>

on:
  workflow_call:
    inputs:
      ref_for_scheduled_build:
        description: 'Reference on which the repo should be checkout for scheduled build. Usually is this name of a branch or a tag.'
        default: ''
        required: false
        type: string

      upstream_workspace:
        description: 'UPSTREAM_WORKSPACE variable for industrial_ci. Usually path to local .repos file.'
        required: false
        default: ''
        type: string
      ros_distro:
        description: 'ROS_DISTRO variable for industrial_ci'
        required: true
        type: string
      ros_repo:
        description: 'ROS_REPO to run for industrial_ci. Possible values: "main", "testing"'
        default: 'main'
        required: false
        type: string
      before_install_upstream_dependencies:
        description: 'BEFORE_INSTALL_UPSTREAM_DEPENDENCIES variable for industrial_ci'
        default: ''
        required: false
        type: string
      ccache_dir:
        description: 'CCache dir that should be used. Relative to github.workspace'
        default: '.ccache'
        required: false
        type: string
      rosdep_skip_keys:
        description: "Skip those keys when doing 'rosdep install'. space-separated list"
        default: ''
        required: false
        type: string

jobs:
  build:
    uses: ./.github/workflows/reusable_ici_build.yml
    with:
      ref_for_scheduled_build: ${{ inputs.ref_for_scheduled_build }}
      upstream_workspace: ${{ inputs.upstream_workspace }}
      ros_distro: ${{ inputs.ros_distro }}
      ros_repo: ${{ inputs.ros_repo }}
      ccache_dir: ${{ inputs.ccache_dir }}
      rosdep_skip_keys: ${{ inputs.rosdep_skip_keys }}

  integration_test:
    needs: build
    uses: ./.github/workflows/reusable_ici_integration_test.yml
    with:
      ref_for_scheduled_build: ${{ inputs.ref_for_scheduled_build }}
      upstream_workspace: ${{ inputs.upstream_workspace }}
      ros_distro: ${{ inputs.ros_distro }}
      ros_repo: ${{ inputs.ros_repo }}
      workspace_cache_key: ${{ needs.build.outputs.workspace_cache_key }}
      ci_image: ${{ needs.build.outputs.ci_image }}
      ci_image_artifact: ${{ needs.build.outputs.ci_image_artifact }}
