---
name: "Build documentation"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '38 2 * * *'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r doc_requirements.txt
      - name: Build documentation
        run: |
          sphinx-build -W -b html ur_calibration/doc _doc_build && \
          sphinx-build -W -b html ur_controllers/doc _doc_build && \
          sphinx-build -W -b html ur_moveit_config/doc _doc_build && \
          sphinx-build -W -b html ur_robot_driver/doc _doc_build
