name: Execution Testing
on:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 22 * * *'
  workflow_dispatch:

jobs:
  semi_binary_test:
    name: semi-binary test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        env:
          - { ROS_DISTRO: rolling, ROS_REPO: main }
          - { ROS_DISTRO: rolling, ROS_REPO: testing }
          - { ROS_DISTRO: galactic, ROS_REPO: main }
          - { ROS_DISTRO: galactic, ROS_REPO: testing }
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver.repos
      DOCKER_RUN_OPTS: --network static_test_net
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
      IMMEDIATE_TEST_OUTPUT: true
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      BASEDIR: ${{ github.workspace }}/.work
      CACHE_PREFIX: ${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-execution
      PARALLEL_TESTS: 2
    steps:
      - uses: actions/checkout@v1
      - name: start ursim
        run: |
          .github/dockerursim/build_and_run_docker_ursim.sh
      # The target directory cache doesn't include the source directory because
      # that comes from the checkout.  See "prepare target_ws for cache" task below
      - name: cache target_ws
        if: ${{ ! matrix.env.CCOV }}
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ env.BASEDIR }}/target_ws
          key: target_ws-${{ env.CACHE_PREFIX }}-${{ hashFiles('**/CMakeLists.txt', '**/package.xml') }}-${{ github.run_id }}
          restore-keys: |
            target_ws-${{ env.CACHE_PREFIX }}-${{ hashFiles('**/CMakeLists.txt', '**/package.xml') }}
      - name: cache ccache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}
            ccache-${{ env.CACHE_PREFIX }}
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - name: prepare target_ws for cache
        if: ${{ always() && ! matrix.env.CCOV }}
        run: |
          du -sh ${{ env.BASEDIR }}/target_ws
          sudo find ${{ env.BASEDIR }}/target_ws -wholename '*/test_results/*' -delete
          sudo rm -rf ${{ env.BASEDIR }}/target_ws/src
          du -sh ${{ env.BASEDIR }}/target_ws
